POST https://medrent.herokuapp.com/api/admin/category
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDc5M2NiY2U4ZTNmNjRiMjgwNjUwN2MiLCJlbWFpbCI6Im92eWFzQGdtYWlsLmNvbSIsImlhdCI6MTYxODU3MzY4NX0.-_EI7nv9yG8AVtPP3Qt5Pc18kK9D_PkIZfZ4Cfjju84


{
	"name":"wheel chair",
	"description":"moving bike"
}

###
GET https://medrent.herokuapp.com/api/admin/products?cat=yes

###
GET http://localhost:3000/api/admin/products?cat=no

###
GET http://localhost:3000/api/shop

###
GET https://medrent.herokuapp.com/api/newRelease

###
GET https://medrent.herokuapp.com/api/product/60797e0a8bc88c3fb4d3c4ef

###
POST https://medrent.herokuapp.com/api/admin/products/
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDc5M2NiY2U4ZTNmNjRiMjgwNjUwN2MiLCJlbWFpbCI6Im92eWFzQGdtYWlsLmNvbSIsImlhdCI6MTYxODU3MzY4NX0.-_EI7nv9yG8AVtPP3Qt5Pc18kK9D_PkIZfZ4Cfjju84

{
	"name":"moter",
    "id": "6079920af1a80c00153d8265",
	"description":"Product 11",
    "price":12000,
    "image":"image.jpg"
}

###
POST https://medrent.herokuapp.com/api/admin/addUser/
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDc5M2NiY2U4ZTNmNjRiMjgwNjUwN2MiLCJlbWFpbCI6Im92eWFzQGdtYWlsLmNvbSIsImlhdCI6MTYxODU3MzY4NX0.-_EI7nv9yG8AVtPP3Qt5Pc18kK9D_PkIZfZ4Cfjju84

{
	"name":"ovyas24",
    "email": "ovyas@gmail.com",
	"password":"admin@123",
    "role":"admin"
}

###
POST https://medrent.herokuapp.com/api/admin/login/
content-type: application/json

{
    "email": "ovyas@gmail.com",
	"password":"admin@123"
}
###
POST https://medrent.herokuapp.com/api/admin/change-password/
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDc5M2NiY2U4ZTNmNjRiMjgwNjUwN2MiLCJlbWFpbCI6Im92eWFzQGdtYWlsLmNvbSIsImlhdCI6MTYxODU3MzY4NX0.-_EI7nv9yG8AVtPP3Qt5Pc18kK9D_PkIZfZ4Cfjju84

{
    "email": "ovyas@gmail.com",
	"opassword":"admin@123",
	"npassword":"admin@1224"
}